name: Secure CI/CD

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - run: |
          pip install flake8
          flake8 .

  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - run: |
          pip install -r requirements.txt pytest
          pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::463518255010:role/BDA-SSM-ROLE
          aws-region: us-east-1

      - name: Deploy to EC2 via SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceIds,Values=${{ secrets.EC2_INSTANCE_ID }}" \
            --parameters 'commands=[
            "set -e",
            "echo Updating code as deploy user...",
            "su - deploy -c \"cd /home/deploy/app && git fetch origin && git reset --hard origin/main\"",
            "echo Installing dependencies as deploy user...",
            "su - deploy -c \"cd /home/deploy/app && source venv/bin/activate && pip install -r requirements.txt\"",
            "echo Restarting app...",
            "systemctl restart app.service",
            "echo Deployment Done"
            ]'